database:
  user: root
  password: root
  net: tcp
  addr: db:3306
  dbname: ecommerce
  allowNativePasswords: true
  params:
    parseTime: true
    charset: utf8mb4
    loc:  Asia/Jakarta

server:
  address: 9090